[package]
name = "hello_world_wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"

[[bin]]
name = "hello_world_native"
path = "src/main.rs"
